#!/usr/bin/env python3
"""Export approved ExerciseRecord v2 rows and generate Metro-safe mobile content."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[3]
DB_DIR = ROOT / "services" / "content" / "db"
MOBILE_DIR = ROOT / "apps" / "mobile"
INDEX_PATH = DB_DIR / "candidates" / "index.json"
JSON_OUTPUT = ROOT / "services" / "content" / "exports" / "exercises.v2.json"
TS_OUTPUT = MOBILE_DIR / "src" / "content" / "generated" / "exerciseCatalogue.generated.ts"

sys.path.insert(0, str(DB_DIR))
import test_export as support  # noqa: E402


def _copy_scalar(db, expression: str) -> str:
    output = support._psql(
        db,
        "\\set ON_ERROR_STOP on\n"
        f"COPY (SELECT ({expression})::text) TO STDOUT;\n",
    )
    return [line.strip() for line in output.splitlines() if line.strip()][-1]


def _candidate_index() -> list[dict]:
    entries = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
    if not isinstance(entries, list) or not entries:
        raise ValueError("candidates/index.json должен содержать непустой массив")
    for entry in entries:
        if set(entry) not in ({"id", "sql"}, {"id", "sql", "publish"}):
            raise ValueError("Каждый кандидат должен содержать id, sql и необязательный publish")
        if "publish" in entry and not isinstance(entry["publish"], bool):
            raise ValueError("Поле publish должно быть boolean")
    return entries


def _export_records() -> list[dict]:
    entries = _candidate_index()
    base = support._pick_ascii_base()
    pgdata = tempfile.mkdtemp(prefix="pgdata_", dir=base)
    support._initdb_ascii_locale_c(pgdata)
    try:
        db = support.pgserver.get_server(pgdata)
    except Exception:
        shutil.rmtree(pgdata, ignore_errors=True)
        raise

    try:
        support._load(db, "schema.sql")
        support._load(db, "seed_reference_data.sql")
        for entry in entries:
            candidate = DB_DIR / "candidates" / entry["sql"]
            support._psql(
                db,
                "\\set ON_ERROR_STOP on\n" + candidate.read_text(encoding="utf-8"),
            )

        records: list[dict] = []
        for entry in entries:
            if not entry.get("publish", True):
                continue
            exercise_id = entry["id"].replace("'", "''")
            can_publish = _copy_scalar(db, f"fn_can_publish('{exercise_id}')")
            if can_publish != "true":
                raise RuntimeError(f"{entry['id']}: publication checklist не пройден")
            record = json.loads(
                _copy_scalar(db, f"fn_export_exercise_record('{exercise_id}')")
            )
            if record["id"] != entry["id"]:
                raise RuntimeError(f"{entry['id']}: экспорт вернул id {record['id']}")
            records.append(record)
        return records
    finally:
        db.cleanup()
        shutil.rmtree(pgdata, ignore_errors=True)


def _require(asset_url: str) -> str:
    if not asset_url.startswith("assets/"):
        raise ValueError(f"Мобильный ассет должен находиться в assets/: {asset_url}")
    asset_path = MOBILE_DIR / asset_url
    if not asset_path.is_file():
        raise FileNotFoundError(f"Не найден ассет: {asset_path}")
    return f"require('../../../{asset_url}')"


def _render_typescript(records: list[dict]) -> str:
    data = json.dumps(records, ensure_ascii=False, indent=2)
    visual_lines: list[str] = []
    for record in records:
        phases = sorted(record["phases"], key=lambda phase: phase["order"])
        thumbnail = next(
            phase for phase in phases if phase["id"] == record["assets"]["thumbnailPhaseId"]
        )
        visual_lines.extend([
            f"  {json.dumps(record['id'])}: {{",
            "    thumbnail: {",
            f"      male: {_require(thumbnail['visual']['assets']['male'])},",
            f"      female: {_require(thumbnail['visual']['assets']['female'])},",
            "    },",
            "    frames: {",
            "      male: [",
        ])
        visual_lines.extend(
            f"        {_require(phase['visual']['assets']['male'])}," for phase in phases
        )
        visual_lines.extend(["      ],", "      female: ["])
        visual_lines.extend(
            f"        {_require(phase['visual']['assets']['female'])}," for phase in phases
        )
        visual_lines.extend(["      ],", "    },"])
        anatomy_asset = record["anatomy"].get("asset")
        if anatomy_asset:
            visual_lines.append(f"    anatomy: {_require(anatomy_asset)},")
        visual_lines.append("  },")

    visuals = "\n".join(visual_lines)
    return (
        "// Generated by services/content/scripts/generate_mobile_catalogue.py.\n"
        "// Do not edit by hand. Metro requires the literal require() calls below.\n\n"
        "import type { ExerciseRecordV2, ExerciseVisualSet } from '../exerciseCatalogue.types';\n\n"
        f"export const generatedExerciseRecords = {data} as const satisfies readonly ExerciseRecordV2[];\n\n"
        "export const generatedExerciseVisuals: Readonly<Record<string, ExerciseVisualSet>> = {\n"
        f"{visuals}\n"
        "};\n"
    )


def _write_or_check(path: Path, content: str, check: bool) -> None:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if check:
        if current != content:
            raise RuntimeError(f"Устарел сгенерированный файл: {path.relative_to(ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="не записывать, а проверить актуальность")
    args = parser.parse_args()
    try:
        records = _export_records()
        json_content = json.dumps(records, ensure_ascii=False, indent=2) + "\n"
        ts_content = _render_typescript(records)
        _write_or_check(JSON_OUTPUT, json_content, args.check)
        _write_or_check(TS_OUTPUT, ts_content, args.check)
    except Exception as exc:
        print(f"ERROR: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1
    action = "проверены" if args.check else "сгенерированы"
    print(f"OK: {len(records)} ExerciseRecord v2 {action}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
