BEGIN;
INSERT INTO anatomy_zones(code,name_en,name_ru,region) VALUES ('abdominals','Abdominals','Мышцы живота','core'),('deltoids','Deltoids','Дельтовидные','upper'),('triceps','Triceps','Трицепсы','upper') ON CONFLICT(code) DO NOTHING;
INSERT INTO exercises(id,name,movement_kind,laterality,experience,style_id,anatomy_style_id,anatomy_status,review_technique,review_phases,review_visuals,review_anatomy,reviewer,reviewed_at,review_notes) VALUES ('bottom-up-press','Жим гири дном вверх','grind','unilateral','advanced','approved-athlete-v1','approved-anatomy-v1','reviewed','source_checked','draft','generated','reviewed','content-pipeline','2026-07-23T00:00:00Z','Две storyboard-фазы сгенерированы; ожидают проверки владельцем и landmark gate.');
INSERT INTO exercise_aliases VALUES ('bottom-up-press','Kettlebell Bottom-up Press'),('bottom-up-press','Перевёрнутый жим гири');
INSERT INTO exercise_phases(id,exercise_id,phase_order,short_name,technique,body_orientation,support,kettlebell_position,body_position,feet_baseline,scale,visual_status) VALUES
 ('bottom-up-rack','bottom-up-press',1,'У плеча','Удерживать гирю дном вверх в правой руке у плеча, предплечье вертикально.','three_quarter','bilateral','Дном вверх над кистью у правого плеча.','Правая стопа немного впереди, корпус вертикален.',0.100,1.000,'generated'),
 ('bottom-up-lockout','bottom-up-press',2,'Над головой','Выжать гирю на прямую правую руку, сохраняя её дном вверх.','three_quarter','bilateral','Дном вверх над правой кистью и плечом.','Рёбра остаются над тазом, запястье нейтрально.',0.100,1.000,'generated');
INSERT INTO phase_assets VALUES ('bottom-up-rack','male','assets/movements/bottom-up-press-rack-male-generated-v1.png'),('bottom-up-lockout','male','assets/movements/bottom-up-press-lockout-male-generated-v1.png'),('bottom-up-rack','female','assets/movements/bottom-up-press-rack-female-generated-v1.png'),('bottom-up-lockout','female','assets/movements/bottom-up-press-lockout-female-generated-v1.png');
UPDATE exercises SET thumbnail_phase_id='bottom-up-rack' WHERE id='bottom-up-press';
INSERT INTO exercise_cues VALUES ('bottom-up-cue-balance','bottom-up-press','Сжимай рукоять и удерживай гирю дном строго вверх.',1);
INSERT INTO exercise_anatomy_zones VALUES ('bottom-up-press','deltoids','primary'),('bottom-up-press','triceps','secondary'),('bottom-up-press','abdominals','secondary');
INSERT INTO exercise_sources VALUES ('bottom-up-src-ace','bottom-up-press','American Council on Exercise','Bottom-up Press','https://www.acefitness.org/resources/everyone/exercise-library/396/bottom-up-press/','professional_standard','2026-07-23');
INSERT INTO source_supports(source_id,target_kind,phase_id,cue_id,zone_code,claim_path) VALUES ('bottom-up-src-ace','phase','bottom-up-rack',NULL,NULL,'phase.bottom-up-rack'),('bottom-up-src-ace','phase','bottom-up-lockout',NULL,NULL,'phase.bottom-up-lockout'),('bottom-up-src-ace','cue',NULL,'bottom-up-cue-balance',NULL,'cue.bottom-up-balance'),('bottom-up-src-ace','anatomy',NULL,NULL,'deltoids','anatomy.deltoids'),('bottom-up-src-ace','anatomy',NULL,NULL,'triceps','anatomy.triceps'),('bottom-up-src-ace','anatomy',NULL,NULL,'abdominals','anatomy.abdominals');
COMMIT;
