BEGIN;
INSERT INTO anatomy_zones(code,name_en,name_ru,region) VALUES ('quadriceps','Quadriceps','Квадрицепсы','lower'),('abdominals','Abdominals','Мышцы живота','core') ON CONFLICT(code) DO NOTHING;
INSERT INTO exercises(id,name,movement_kind,laterality,experience,style_id,anatomy_style_id,anatomy_status,review_technique,review_phases,review_visuals,review_anatomy,reviewer,reviewed_at,review_notes) VALUES ('front-rack-squat','Фронтальный присед с гирей','grind','unilateral','intermediate','approved-athlete-v1','approved-anatomy-v1','reviewed','source_checked','draft','generated','reviewed','content-pipeline','2026-07-23T00:00:00Z','Две storyboard-фазы сгенерированы; ожидают проверки владельцем и landmark gate.');
INSERT INTO exercise_aliases VALUES ('front-rack-squat','Single Kettlebell Front Squat'),('front-rack-squat','Присед с гирей в стойке');
INSERT INTO exercise_phases(id,exercise_id,phase_order,short_name,technique,body_orientation,support,kettlebell_position,body_position,feet_baseline,scale,visual_status) VALUES
 ('front-squat-stand','front-rack-squat',1,'Стойка','Стоять устойчиво с гирей в правой стойке у плеча.','three_quarter','bilateral','В правой стойке у плеча.','Таз и колени разогнуты, грудная клетка над тазом.',0.100,1.000,'generated'),
 ('front-squat-bottom','front-rack-squat',2,'Нижняя позиция','Согнуть таз и колени, сохраняя гирю у плеча и вертикальный корпус.','three_quarter','bilateral','Остаётся в правой стойке.','Пятки на полу, колени направлены по носкам, таз опущен.',0.100,1.000,'generated');
INSERT INTO phase_assets VALUES ('front-squat-stand','male','assets/movements/front-squat-stand-male-generated-v1.png'),('front-squat-bottom','male','assets/movements/front-squat-bottom-male-generated-v1.png'),('front-squat-stand','female','assets/movements/front-squat-stand-female-generated-v1.png'),('front-squat-bottom','female','assets/movements/front-squat-bottom-female-generated-v1.png');
UPDATE exercises SET thumbnail_phase_id='front-squat-stand' WHERE id='front-rack-squat';
INSERT INTO exercise_cues VALUES ('front-squat-cue-upright','front-rack-squat','Держи грудную клетку поднятой, а колени направляй по носкам.',1);
INSERT INTO exercise_anatomy_zones VALUES ('front-rack-squat','quadriceps','primary'),('front-rack-squat','glutes','primary'),('front-rack-squat','abdominals','secondary');
INSERT INTO exercise_sources VALUES ('front-squat-src-nasm','front-rack-squat','National Academy of Sports Medicine','Kettlebell Front Squat','https://www.nasm.org/resource-center/exercise-library/kettlebell-front-squat','professional_standard','2026-07-23');
INSERT INTO source_supports(source_id,target_kind,phase_id,cue_id,zone_code,claim_path) VALUES ('front-squat-src-nasm','phase','front-squat-stand',NULL,NULL,'phase.front-squat-stand'),('front-squat-src-nasm','phase','front-squat-bottom',NULL,NULL,'phase.front-squat-bottom'),('front-squat-src-nasm','cue',NULL,'front-squat-cue-upright',NULL,'cue.front-squat-upright'),('front-squat-src-nasm','anatomy',NULL,NULL,'quadriceps','anatomy.quadriceps'),('front-squat-src-nasm','anatomy',NULL,NULL,'glutes','anatomy.glutes'),('front-squat-src-nasm','anatomy',NULL,NULL,'abdominals','anatomy.abdominals');
COMMIT;
