BEGIN;
INSERT INTO anatomy_zones(code,name_en,name_ru,region) VALUES ('abdominals','Abdominals','Мышцы живота','core'),('deltoids','Deltoids','Дельтовидные','upper') ON CONFLICT(code) DO NOTHING;
INSERT INTO exercises(id,name,movement_kind,laterality,experience,style_id,anatomy_style_id,anatomy_status,review_technique,review_phases,review_visuals,review_anatomy,reviewer,reviewed_at,review_notes) VALUES ('high-windmill','Высокая мельница','grind','unilateral','advanced','approved-athlete-v1','approved-anatomy-v1','reviewed','source_checked','draft','generated','reviewed','content-pipeline','2026-07-23T00:00:00Z','Две storyboard-фазы сгенерированы; ожидают проверки владельцем и landmark gate.');
INSERT INTO exercise_aliases VALUES ('high-windmill','High Windmill'),('high-windmill','Мельница с гирей над головой');
INSERT INTO exercise_phases(id,exercise_id,phase_order,short_name,technique,body_orientation,support,kettlebell_position,body_position,feet_baseline,scale,visual_status) VALUES
 ('windmill-stand','high-windmill',1,'Стойка','Зафиксировать правую руку с гирей вертикально над плечом.','three_quarter','bilateral','Над правым плечом на прямой руке.','Широкая устойчивая стойка, корпус вертикален.',0.100,1.000,'generated'),
 ('windmill-hinge','high-windmill',2,'Наклон','Отвести таз вправо и наклониться к левой ноге, сохраняя правую руку вертикальной.','three_quarter','bilateral','Остаётся над правым плечом на прямой руке.','Позвоночник длинный, взгляд направлен на гирю, обе стопы на полу.',0.100,1.000,'generated');
INSERT INTO phase_assets VALUES ('windmill-stand','male','assets/movements/high-windmill-stand-male-generated-v1.png'),('windmill-hinge','male','assets/movements/high-windmill-hinge-male-generated-v1.png'),('windmill-stand','female','assets/movements/high-windmill-stand-female-generated-v1.png'),('windmill-hinge','female','assets/movements/high-windmill-hinge-female-generated-v1.png');
UPDATE exercises SET thumbnail_phase_id='windmill-hinge' WHERE id='high-windmill';
INSERT INTO exercise_cues VALUES ('windmill-cue-arm','high-windmill','Сохраняй руку с гирей прямой и смотри на гирю.',1);
INSERT INTO exercise_anatomy_zones VALUES ('high-windmill','glutes','primary'),('high-windmill','hamstrings','secondary'),('high-windmill','deltoids','secondary'),('high-windmill','abdominals','secondary');
INSERT INTO exercise_sources VALUES ('windmill-src-ace','high-windmill','American Council on Exercise','High Windmill','https://www.acefitness.org/resources/everyone/exercise-library/386/high-windmill/','professional_standard','2026-07-23');
INSERT INTO source_supports(source_id,target_kind,phase_id,cue_id,zone_code,claim_path) VALUES ('windmill-src-ace','phase','windmill-stand',NULL,NULL,'phase.windmill-stand'),('windmill-src-ace','phase','windmill-hinge',NULL,NULL,'phase.windmill-hinge'),('windmill-src-ace','cue',NULL,'windmill-cue-arm',NULL,'cue.windmill-arm'),('windmill-src-ace','anatomy',NULL,NULL,'glutes','anatomy.glutes'),('windmill-src-ace','anatomy',NULL,NULL,'hamstrings','anatomy.hamstrings'),('windmill-src-ace','anatomy',NULL,NULL,'deltoids','anatomy.deltoids'),('windmill-src-ace','anatomy',NULL,NULL,'abdominals','anatomy.abdominals');
COMMIT;
