BEGIN;
INSERT INTO anatomy_zones(code,name_en,name_ru,region) VALUES ('abdominals','Abdominals','Мышцы живота','core'),('deltoids','Deltoids','Дельтовидные','upper') ON CONFLICT(code) DO NOTHING;
INSERT INTO exercises(id,name,movement_kind,laterality,experience,style_id,anatomy_style_id,anatomy_status,review_technique,review_phases,review_visuals,review_anatomy,reviewer,reviewed_at,review_notes) VALUES ('kettlebell-figure-eight','Восьмёрка с гирей','complex','alternating','intermediate','approved-athlete-v1','approved-anatomy-v1','reviewed','source_checked','draft','generated','reviewed','content-pipeline','2026-07-23T00:00:00Z','Три storyboard-фазы сгенерированы; ожидают проверки владельцем и landmark gate.');
INSERT INTO exercise_aliases VALUES ('kettlebell-figure-eight','Kettlebell Figure Eight'),('kettlebell-figure-eight','Передача гири восьмёркой');
INSERT INTO exercise_phases(id,exercise_id,phase_order,short_name,technique,body_orientation,support,kettlebell_position,body_position,feet_baseline,scale,visual_status) VALUES
 ('figure-eight-left','kettlebell-figure-eight',1,'Слева','Провести гирю левой рукой вокруг левой ноги к пространству за коленом.','three_quarter','bilateral','Снаружи и позади левой ноги.','Широкая стойка, таз опущен, спина нейтральна.',0.100,1.000,'generated'),
 ('figure-eight-pass','kettlebell-figure-eight',2,'Передача','Передать рукоять из левой руки в правую за ногами.','three_quarter','transition','Между бёдрами за линией ног.','Высота стойки и положение корпуса сохраняются.',0.100,1.000,'generated'),
 ('figure-eight-right','kettlebell-figure-eight',3,'Справа','Провести гирю правой рукой вокруг правой ноги вперёд.','three_quarter','bilateral','Снаружи правой ноги.','Широкая стойка и нейтральная спина сохраняются.',0.100,1.000,'generated');
INSERT INTO phase_assets VALUES ('figure-eight-left','male','assets/movements/figure-eight-left-male-generated-v1.png'),('figure-eight-pass','male','assets/movements/figure-eight-pass-male-generated-v1.png'),('figure-eight-right','male','assets/movements/figure-eight-right-male-generated-v1.png'),('figure-eight-left','female','assets/movements/figure-eight-left-female-generated-v1.png'),('figure-eight-pass','female','assets/movements/figure-eight-pass-female-generated-v1.png'),('figure-eight-right','female','assets/movements/figure-eight-right-female-generated-v1.png');
UPDATE exercises SET thumbnail_phase_id='figure-eight-pass' WHERE id='kettlebell-figure-eight';
INSERT INTO exercise_cues VALUES ('figure-eight-cue-still','kettlebell-figure-eight','Сохраняй высоту стойки и передавай гирю близко к ногам.',1);
INSERT INTO exercise_anatomy_zones VALUES ('kettlebell-figure-eight','glutes','primary'),('kettlebell-figure-eight','abdominals','secondary'),('kettlebell-figure-eight','deltoids','secondary');
INSERT INTO exercise_sources VALUES ('figure-eight-src-ace','kettlebell-figure-eight','American Council on Exercise','Figure Eight','https://www.acefitness.org/resources/everyone/exercise-library/382/figure-eight/','professional_standard','2026-07-23');
INSERT INTO source_supports(source_id,target_kind,phase_id,cue_id,zone_code,claim_path) VALUES ('figure-eight-src-ace','phase','figure-eight-left',NULL,NULL,'phase.figure-eight-left'),('figure-eight-src-ace','phase','figure-eight-pass',NULL,NULL,'phase.figure-eight-pass'),('figure-eight-src-ace','phase','figure-eight-right',NULL,NULL,'phase.figure-eight-right'),('figure-eight-src-ace','cue',NULL,'figure-eight-cue-still',NULL,'cue.figure-eight-still'),('figure-eight-src-ace','anatomy',NULL,NULL,'glutes','anatomy.glutes'),('figure-eight-src-ace','anatomy',NULL,NULL,'abdominals','anatomy.abdominals'),('figure-eight-src-ace','anatomy',NULL,NULL,'deltoids','anatomy.deltoids');
COMMIT;
